version: "2"         # required to adjust maintainability checks
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-82
    config:
      file: .rubocop.yml
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
exclude_patterns:
  - 'config/'
  - 'db/'
  - 'spec/'
  - '.rubocop.yml'
  - '.rubocop_todo.yml'
