version: "2"         # required to adjust maintainability checks
checks:
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-82
    config:
      file: .rubocop.yml
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
    exclude_fingerprints:
    - 5d80bde618c0836393581d7c8eb9ca61600a255f
exclude_patterns:
  - 'config/'
  - 'db/'
  - 'spec/'
  - '.rubocop.yml'
  - '.rubocop_todo.yml'
