
AllCops:
  # Prior to upgrading to Rails 5.0 we can change this, but right now it will break too many things
  TargetRailsVersion: 4.0
  TargetRubyVersion: 2.3
  Include:
    - '**/config.ru'
    - '**/Rakefile'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'log/**/*'

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/scorecard.rb'
    - 'app/models/ipeds_ic.rb'
    - 'app/models/ipeds_ic_ay.rb'
    - 'app/models/ipeds_ic_py.rb'
    - 'app/models/institution.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/models/institution_builder.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/institution_builder.rb'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/**/*.rb'

Naming/FileName:
  Exclude:
    - 'Guardfile'

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/user.rb'

Lint/BooleanSymbol:
  Exclude:
    - 'app/controllers/v0/institutions_controller.rb'
