AllCops:
  Include:
    - '**/config.ru'
    - '**/Rakefile'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'log/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/models/concerns/**/*'

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - 'lib/**/*.rb'
