AllCops:
  Include:
    - '**/config.ru'
    - '**/Rakefile'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'log/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/scorecard.rb'
    - 'app/models/ipeds_ic.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/**/*.rb'

Style/Tab:
  Enabled: false
