AllCops:
  Include:
    - '**/config.ru'
    - '**/Rakefile'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - 'lib/**/*.rb'
