language: ruby

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - rake db:migrate

branches:
    only:
        - master

script:
  - git branch
  - bundle exec rspec

bundler_args: "--without development"
cache:
  - bundler

notifications:
  email: false
