FROM ruby:3.3.6-slim-bookworm

RUN apt-get update && apt-get install -y \
  build-essential \
  chromium \
  fonts-liberation \
  && rm -rf /var/lib/apt/lists/*

RUN gem install ferrum

WORKDIR /app

COPY test_ferrum.rb .
