# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.3.0
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim-bookworm as base

# Rails app lives here
WORKDIR /rails

# Set default (production) values. Override ex: --build-arg="RAILS_ENV='development'"
ARG RAILS_ENV="production" \
    BUNDLE_WITHOUT="development" \
    USER_ID=1000

# Set environment
ENV RAILS_ENV=$RAILS_ENV \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT=$BUNDLE_WITHOUT

# Create group and nonroot user
RUN groupadd --gid $USER_ID gi-bill-data-service && \
    useradd --uid $USER_ID --gid gi-bill-data-service --create-home --shell /bin/bash gi-bill-data-service

# Throw-away build stage to reduce size of final image
FROM base as build

# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config

# Install application gems
COPY Gemfile Gemfile.lock ./

RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile

# Copy application code, changing ownership to nonroot user/group
COPY --chown=gi-bill-data-service:gi-bill-data-service . .

# Don't include /sample_csvs in production 
RUN if [ "$RAILS_ENV" = "production" ]; then rm -rf ./sample_csvs; fi

# Precompile bootsnap code for faster boot times
RUN bundle exec bootsnap precompile app/ lib/

# Final stage for app image
FROM base

# Install packages needed for deployment
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libvips postgresql-client nodejs && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Copy built artifacts: gems, application
COPY --from=build --chown=gi-bill-data-service:gi-bill-data-service /usr/local/bundle /usr/local/bundle
COPY --from=build --chown=gi-bill-data-service:gi-bill-data-service /rails /rails

# TODO - maybe perform in Base layer?
# Clone platform-va-ca-certificate and copy certs
# WORKDIR /srv
# RUN git clone --depth 1 https://github.com/department-of-veterans-affairs/platform-va-ca-certificate && \
#     cp platform-va-ca-certificate/VA*.cer /tmp && \
#     /bin/bash platform-va-ca-certificate/debian-ubuntu/install-certs.sh
# WORKDIR /srv/gi-bill-data-service/src

USER gi-bill-data-service:gi-bill-data-service

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD ["./bin/rails", "server", "--binding", "0.0.0.0"]
