generic:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Weam:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Crosswalk:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

EightKey:
  skip_lines: 1
  col_sep: ','
  row_sep: "\r\n"

Accreditation:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

ArfGiBill:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Scorecard:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

P911Tf:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

P911Yr:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Vsoc:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Sva:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Sec702:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Sec702School:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Mou:
  skip_lines: 1
  col_sep: ','
  row_sep: "\r\n"

Hcm:
  skip_lines: 2
  col_sep: ','
  row_sep: "\r\n"

Settlement:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

IpedsIc:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

IpedsHd:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

IpedsIcAy:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

IpedsIcPy:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Complaint:
  skip_lines: 7
  col_sep: ','
  row_sep: "\r\n"

Outcome:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

Institution:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

CalculatorConstant:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

YellowRibbonProgramSource:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

IpedsCipCode:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

StemCipCode:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"

SchoolClosure:
  skip_lines: 0
  col_sep: ','
  row_sep: "\r\n"
