###############################################################################
## This is the GIBCT staging database configuration, and configures the 
## connecton to the GIBCT database.
###############################################################################
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gi_bill_comparison_tool_development

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  <<: *default
  database: gi_bill_comparison_tool_production
