common: &default_settings
  app_name: GIDS
  log_level: info


development:
  <<: *default_settings
  app_name: GIDS (Development)

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: GIDS (Staging)

production:
  <<: *default_settings
