active_record:
  batch_size:
    find_each: 5000
    import: 50000

archiver:
  archive: true

csv_upload:
  column_separators:
    - "|"
    - ","

scorecard:
  url: "https://api.data.gov/ed/collegescorecard/v1"
  api_key: <%= ENV['SCORECARD_API_KEY'] %>

environment: <%= ENV['DEPLOYMENT_ENV'] %>

institution_name_similarity_threshold: .1
