name: "Build And Publish"
run-name: "Build And Publish"

# Trigger on push and also allow manual run
on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  build:
    uses: department-of-veterans-affairs/vsp-github-actions/.github/workflows/build-and-publish.yaml@main
    secrets: inherit
