name: "Build And Publish"
run-name: "Build And Publish"

# Trigger on push and also allow manual run
on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: department-of-veterans-affairs/prt-github-workflows/.github/workflows/build-and-publish.yaml@main
    secrets: inherit
