name: build docker image
on:
  push:
    branches:
      - tskinn-k8s-docker-update

jobs:
  mirror:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-gov-west-1"
      - name: Log into ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v2
      - name: Tag/Push to AWS ECR
        id: tag-image
        env:
          ECR_REPO: ${{ steps.login-ecr.outputs.registry }}/dsva-gibct-data-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --tag ${ECR_REPO}:${IMAGE_TAG} --target k8s -- $PWD
          docker build --tag ${ECR_REPO}:latest --target k8s -- $PWD
          docker push ${ECR_REPO}:${IMAGE_TAG}
          docker push ${ECR_REPO}:latest
          echo "::set-output name=image::$ECR_REPO:$IMAGE_TAG"
