name: CI

on:
  push:
    branches: [main, master] # future proofing if we get around to renaming master to main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  checks: write

jobs:
  linting_and_security:
    name: Linting and Security
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
          bundler-cache: true

      - name: Run bundle-audit (checks gems for CVE issues)
        run: bundle exec bundle-audit check --update

      - name: Run Rubocop
        run: bundle exec rubocop --parallel --format github

      - name: Run Brakeman
        run: bundle exec brakeman --ensure-latest --confidence-level=2 --format github

      - name: Add Lint Failure label
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          number: ${{ github.event.pull_request.number }}
          labels: lint-failure

      - name: Remove Lint Failure label
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          number: ${{ github.event.pull_request.number }}
          labels: lint-failure

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: linting_and_security
    permissions: write-all
    env:
      CI: true
      RAILS_ENV: test
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker compose -f docker-compose.test.yml build

      - name: Setup Database
        run: |
          docker compose -f docker-compose.test.yml run --rm gibct bash --login -c "bin/rails db:setup db:migrate"

      - name: Setup CodeClimate
        if: env.CC_TEST_REPORTER_ID != ''
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run Specs
        run: |
          docker compose -f docker-compose.test.yml run --rm gibct bash --login -c "bin/rails spec"

      - name: Report Coverage to CodeClimate
        if: env.CC_TEST_REPORTER_ID != '' && always()
        run: |
          ./cc-test-reporter after-build -t simplecov --exit-code $?

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          if-no-files-found: ignore

      - name: Add Test Failure label
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          number: ${{ github.event.pull_request.number }}
          labels: test-failure

      - name: Remove Test Failure label
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          number: ${{ github.event.pull_request.number }}
          labels: test-failure

      - name: Cleanup
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down
          rm -rf data || true

  # only run on push. Skip for pull requests
  build:
    name: Build
    needs: tests
    if: github.event_name == 'push'
    permissions:
      actions: write
      artifact-metadata: write
      attestations: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      issues: write
      models: read
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      statuses: write
      security-events: write
      id-token: write
    uses: department-of-veterans-affairs/vsp-github-actions/.github/workflows/build-and-publish.yaml@main
    secrets: inherit

  deploy:
    name: Deploy
    needs: build # build has a gate on push, so this won't run when build doesn't run (pull requests)
    permissions:
      id-token: write
      contents: read
    uses: department-of-veterans-affairs/gibct-data-service/.github/workflows/deploy-template.yml@master
    with:
      ecr_repository: "gibct-data-service"
      manifests_directory: "gi-bill-data-service"
      auto_deploy_envs: "dev"
      commit_sha: ${{ github.sha }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
