name: "Deploy Environments"
run-name: "Deploy Environments"

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-workflow]
  
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v**'
    # branches:  # This is for testing only - This will trigger deploys in this repo on every push
    #   - '**'

jobs:
  Deploy-Envs:
    uses: department-of-veterans-affairs/gibct-data-service/.github/workflows/deploy-template.yml@main
    with:
      ecr_repository: "gibct-data-service"
      manifests_directory: "gibct-data-service"
      auto_deploy_envs: "dev"
      commit_sha: ${{ github.sha }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
